### ISSUE TITLE
how to import this into android studio

### ISSUE THREAD

**Issue by frostmournex** [NordicSemiconductor/Android-nRF-Toolbox#1]
Hi everyone, 

I am having some difficulty to get this project imported into android studio. I have cloned both the nrf toolbox and dfu library from github, I tried to open the project by selecting building.gradle, however android studio keeps prompting me : " Configuration with name 'default' is not found. "

Setup, Android Studio 1.0.1, API 22 with latest build tool 22.0.1.

Any input is appreciated. Thanks.

**Comment by philips77** [comment]
Hi,
Please check the project Android-nRF-Beacon on our GitHub account. There is a detailed information how to import both projects: DFU Library and nRF Beacon. nRF Toolbox should be imported the same way. Content of this repo should be cloned to nRFToolbox folder, instead of nRFBeacon. Hope it helped.
