### ISSUE TITLE
"DFU device not found" error

### ISSUE THREAD

**Issue by CptJackieSparrow** [NordicSemiconductor/Android-nRF-Toolbox#20]
I'm trying to upgrade firmware of iwown i5 Plus bracelet (not working without connecting it to power, so i'm trying to restore it), but everytime i try to upload firmware to Braceli-0164 (my device name), i'm getting that "DFU device not found" error.

**Comment by philips77** [comment]
Hi,
We are not the manufacturer of i5 Plus device nor it's firmware.
Although, I saw they use our apps tu upgrade/downgrade the firmware.

I got many questions like yours regarding this topic and the only thing I can do is to point you to some videos showing how others do it: https://www.youtube.com/watch?v=tsWey15LNe8 
You may use nRF Connect app instead of nRF Toolbox as it ensures the device cache is cleared before doing DFU so no old services are used. Also, I think it requires some command/other app to switch it to DFU bootloader mode.
